export enum MaterialTag {
  VEGAN = 'VEGAN',
  RENEWABLE = 'RENEWABLE',
  REUSABLE = 'REUSABLE',
  LOCALLY_ABUNDANT = 'LOCALLY ABUNDANT',
  BY_PRODUCT = 'BY-PRODUCT',
  HOME_COMPOSTABLE = 'HOME COMPOSTABLE'
}
